build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
config:
  validation: true
  warningsAsErrors: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''
comments:
  active: true
  UndocumentedPublicClass:
    active: false
    excludes: &testDirs
      - '**/test/**'
      - '**/androidTest/**'
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: true
    exclude: *testDirs
  UndocumentedPublicProperty:
    active: false
complexity:
  TooManyFunctions:
    active: true
    exclude: *testDirs
    thresholdInFiles: 11
    thresholdInClasses: 11
    thresholdInInterfaces: 11
    thresholdInObjects: 11
    thresholdInEnums: 11
    ignoreDeprecated: true
    ignorePrivate: false
    ignoreOverridden: true
  NestedBlockDepth:
    active: true
    threshold: 4
empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyTryBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true
exceptions:
  active: true
  SwallowedException:
    active: false
style:
  active: true
  MaxLineLength:
    active: true
    exclude: *testDirs
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: true
  ReturnCount:
    active: true
    max: 3
  PreferToOverPairSyntax:
    active: true
